services:
  ravendb:
    image: ravendb/ravendb
    container_name: RavenDbGHAction
    ports:
      - "8081:8080"
    environment:
      - RAVEN_License=${RAVEN_LICENSE}
      - RAVEN_DATABASE=testdapr
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    restart: unless-stopped